/* TERMINAL FILE FINDER (CONFIGURATION) [HEADER] */
#ifndef _CONF_HPP
#define _CONF_HPP

bool is_installed(void); // CHECK IF USER INSTALLED THE APPLICATION IF EXIST THEN RETURN TRUE

#endif /* MADE BY @hanilr */